### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by mtvector**
Fix for invalid constraints, forgot to PR before :)

### CODE REVIEW

**Comment by UCDNJJ** [comment]
@mtvector Looks great! I was thinking about this the other week: Should we keep track of all cell ids that are flagged by a specific constraint, independent of all other constraints?

**Review by UCDNJJ — COMMENTED** [review]
Review-

**Comment by mtvector** [comment]
> @mtvector Looks great! I was thinking about this the other week: Should we keep track of all cell ids that are flagged by a specific constraint, independent of all other constraints?

Oh haha that's the whole reason I designed it this way, I forgot to collect the cell IDs and return them. I'll do that

**Comment by mtvector** [comment]
Jk it actually did it already, I just had a bug so it didn't work correctly, the filtered cells for each column+constraint should be saved in adata.uns['qc_filtered']

**Pull request merged**
